version: '3'
services:
  artifactory:
    image: zygon/artifactory-rpi
    build: .
    container_name: artifactory
    ports:
     - 80:8081
    volumes:
     - /data/artifactory/data:/artifactory/data
     - /data/artifactory/logs:/artifactory/logs
     - /data/artifactory/backup:/artifactory/backup
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
